name: Deploy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: 
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
    
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Deploy to cloud.gov
  #       uses: cloud-gov/cg-cli-tools@main
  #       with: 
  #         cf_username: ${{ secrets.CG_USERNAME }}
  #         cf_password: ${{ secrets.CG_PASSWORD }}
  #         cf_org: ${{ secrets.CF_ORG }}
  #         cf_space: ${{ secrets.CF_SPACE }}
